"""Initial migration

Revision ID: 296da030d42f
Revises: 04722d5a196c
Create Date: 2025-08-22 12:10:18.843673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296da030d42f'
down_revision: Union[str, Sequence[str], None] = '04722d5a196c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('stars', sa.Integer(), nullable=False))
    op.add_column('hotels', sa.Column('has_spa', sa.Boolean(), nullable=False))
    op.add_column('hotels', sa.Column('has_swiming_pooo', sa.Boolean(), nullable=False))
    op.drop_column('hotels', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('hotels', 'has_swiming_pooo')
    op.drop_column('hotels', 'has_spa')
    op.drop_column('hotels', 'stars')
    # ### end Alembic commands ###
